version: "3"
services:
  zway:
    container_name: zway
    logging:
      driver: journald
    build:
      context: zway
    environment:
      TZ: "America/Chicago"
    volumes:
      - zway:/opt/z-way-server/
    ports:
      - "127.0.0.1:8083:8083"
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:arm32v6
    logging:
      driver: journald
    environment:
      TZ: "America/Chicago"
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
volumes:
  zway: